import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Providers from "@/lib/Providers";
import ClientToast from "@/lib/ClientToast";
import Navigation from "@/components/Navigation/Navigation";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Strainbase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={`${inter.className} dark:bg-black dark:text-white`}>
        <Providers>
          <Navigation />
          <div className="pt-20">{children}</div>
          <ClientToast />
        </Providers>
      </body>
    </html>
  );
}
